# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DiplomaUd' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DiplomaUd

  target 'DiplomaUd-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

    pod 'react-native-pdf', :path => '../node_modules/react-native-pdf'

    pod 'RNShare', :path => '../node_modules/react-native-share'

    pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  end

  target 'DiplomaUdTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'DiplomaUd-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DiplomaUd-tvOS

  target 'DiplomaUd-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'DCTAuth', :git => 'https://github.com/danielctull/DCTAuth.git'
